## Full-box SSLO Use Case: Outbound GW
## Builds:
## - TAP inspection service
## - Inline L2 inspection service
## - Service chain
## - Security policy
## - Outbound SSL config
## - Outbound gateway topology
---
- name: Create an SSLO Full-box Use Case - Outbound GW
  hosts: all
  connection: httpapi
  gather_facts: false

  collections:
    - f5networks.f5_bigip

  vars:
    ansible_host: "{{ lookup('ansible.builtin.env', 'BIGHOST') }}"
    ansible_httpapi_password: "{{ lookup('ansible.builtin.env', 'BIGPASS') }}"
    ansible_httpapi_port: 443
    ansible_user: "admin"
    ansible_network_os: f5networks.f5_bigip.bigip
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no

  tasks:
    - fail:
        msg: "Environment variable 'BIGHOST' is empty. Do `export BIGHOST='host'`"
      when: lookup('env', 'BIGHOST') | length == 0

    - fail:
        msg: "Environment variable 'BIGPASS' is empty. Do `export BIGPASS='pass'`"
      when: lookup('env', 'BIGPASS') | length == 0

    ## Create Inspection Services
    - name: Create an SSLO TAP Inspection Service
      bigip_sslo_service_tap:
        name: "insp_tap"
        devices:
          interface: "1.3"
        mac_address: "12:12:12:12:12:12"

    - name: Create an SSLO Inline L2 Inspection Service
      bigip_sslo_service_layer2:
        name: "insp_inline_l2"
        devices:
          - name: "FEYE1"
            ratio: 1
            interface_in: "1.4"
            interface_out: "1.5"
        port_remap: 8080

    ## Create a Service Chain
    - name: Create an SSLO Service Chain
      bigip_sslo_config_service_chain:
        name: "sc_all_services"
        services:
          - service_name: "insp_tap"
            type: "tap"
          - service_name: "insp_inline_l2"
            type: "L2"

    ## Create an SSLO policy
    - name: Create an SSLO Outbound Policy
      bigip_sslo_config_policy:
        name: "my_policy_outbound"
        policy_consumer: "outbound"
        policy_rules:
          - name: "bypass_pii"
            policy_action: "allow"
            ssl_action: "bypass"
            service_chain: "sc_all_services"
            conditions:
              - condition_type: "category_lookup_all"
                condition_option_category:
                  - "Financial Data and Services"
                  - "Health and Medicine"
        default_rule:
          allow_block: "allow"
          tls_intercept: "intercept"
          service_chain: "sc_all_services"

    ## Create outbound SSL settings
    - name: Create an SSLO Outbound SSL Config
      bigip_sslo_config_ssl:
        name: "my_ssl_outbound"
        client_settings:
          proxy_type: "forward"
          ca_cert: "/Common/subrsa.f5labs.com"
          ca_key: "/Common/subrsa.f5labs.com"
        server_settings:
          ca_bundle: "/Common/ca-bundle.crt"
    
    ## Create an outbound GW topology
    - name: Create an SSLO outbound gateway topology
      bigip_sslo_config_topology:
        name: "my_sslo_out_gw"
        topology_type: "outbound_l3"
        vlans:
          - "/Common/client-vlan"
        gateway: "iplist"
        gateway_list:
          - ip: "10.1.60.1"
        snat: "automap"
        ssl_settings: "my_ssl_outbound"
        profile_scope: "public"
        security_policy: "my_policy_outbound"
