---
- name: Create an SSLO Inspection Service - HTTP Explicit Proxy
  hosts: all
  connection: httpapi
  gather_facts: false

  collections:
    - f5networks.f5_bigip

  vars:
    ansible_host: "{{ lookup('ansible.builtin.env', 'BIGHOST') }}"
    ansible_httpapi_password: "{{ lookup('ansible.builtin.env', 'BIGPASS') }}"
    ansible_httpapi_port: 443
    ansible_user: "admin"
    ansible_network_os: f5networks.f5_bigip.bigip
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no

  tasks:
    - fail:
        msg: "Environment variable 'BIGHOST' is empty. Do `export BIGHOST='host'`"
      when: lookup('env', 'BIGHOST') | length == 0

    - fail:
        msg: "Environment variable 'BIGPASS' is empty. Do `export BIGPASS='pass'`"
      when: lookup('env', 'BIGPASS') | length == 0

    - name: Create an SSLO HTTP EP Inspection Service
      bigip_sslo_service_http:
        name: "insp_httpep"
        proxy_type: "explicit"
        auto_manage: false
        devices_to:
          interface: "1.2"
          tag: 30
          self_ip: "198.19.96.7"
          netmask: "255.255.255.128"
        devices_from:
          interface: "1.2"
          tag: 40
          self_ip: "198.19.96.245"
          netmask: "255.255.255.128"
        devices:
          - ip: "198.19.96.30"
            port: 3128
        #dump_json: true
        #state: absent
      register: json_response

    - debug:
        msg: "{{ json_response }}"
