---
- name: Create an Outbound Policy
  hosts: all
  connection: httpapi
  gather_facts: false

  collections:
    - f5networks.f5_bigip

  vars:
    ansible_host: "{{ lookup('ansible.builtin.env', 'BIGHOST') }}"
    ansible_httpapi_password: "{{ lookup('ansible.builtin.env', 'BIGPASS') }}"
    ansible_httpapi_port: 443
    ansible_user: "admin"
    ansible_network_os: f5networks.f5_bigip.bigip
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no

  tasks:
    - fail:
        msg: "Environment variable 'BIGHOST' is empty. Do `export BIGHOST='host'`"
      when: lookup('env', 'BIGHOST') | length == 0

    - fail:
        msg: "Environment variable 'BIGPASS' is empty. Do `export BIGPASS='pass'`"
      when: lookup('env', 'BIGPASS') | length == 0

    - name: Create an SSLO Outbound Policy
      bigip_sslo_config_policy:
        name: "my_policy_outbound"
        policy_consumer: "outbound"
        policy_rules:
          - name: "bypass_pii"
            policy_action: "allow"
            ssl_action: "bypass"
            service_chain: "my_service_chain"
            conditions:
              - condition_type: "category_lookup_all"
                condition_option_category:
                  - "Financial Data and Services"
                  - "Health and Medicine"
        default_rule:
          allow_block: "allow"
          tls_intercept: "intercept"
          service_chain: "my_service_chain"
        #dump_json: true
        #state: absent
      register: json_response

    - debug:
        msg: "{{ json_response }}"
